<html>

<head>
<style>
table, th , td  {
  border: 1px solid grey;
  border-collapse: collapse;
  padding: 5px;
}
table tr:nth-child(odd)	{
  background-color: #f1f1f1;
}
table tr:nth-child(even) {
  background-color: #ffffff;
}
</style>
<script src= "http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js"></script>
</head>


<body>

<div ng-app="" ng-controller="vendorsController">

<table>
  <tr ng-repeat="x in vendors | orderBy:'Description'">
    <td ng-if="isNumber(x.AuthorizedVendorLogoImageID)">{{ x.Description }}</td>
    <td ng-if="isNumber(x.AuthorizedVendorLogoImageID)"><img src="/img/?ID={{ x.AuthorizedVendorLogoImageID }}"></td>
  </tr>
</table>

</div>


<script>
function vendorsController($scope,$http) {
    $http.get("http://www.netcomlearning.com/inc/vendor.json.php")
    	.success(function(response) {$scope.vendors = response;});

    $scope.isNumber = function (value) {
        return angular.isNumber(value);
    };
}
</script> 


</body>
</html>
